# Generated by Django 5.2.17 on 2026-09-11 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('credits', models.PositiveSmallIntegerField()),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('degree', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=50)),
                ('minimum_credits', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CurriculumCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('BASE', 'Base'), ('SPECIALIZED', 'Specialized'), ('ELECTIVE', 'Elective'), ('GENERAL', 'General')], max_length=20)),
                ('recommended_semester', models.PositiveSmallIntegerField()),
                ('is_mandatory', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_courses', to='planner.course')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_courses', to='planner.curriculum')),
            ],
        ),
        migrations.CreateModel(
            name='Prerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisites', to='planner.course')),
                ('prerequisite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_for', to='planner.course')),
            ],
        ),
        migrations.CreateModel(
            name='RequirementGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('MANDATORY', 'Mandatory'), ('CHOOSE_COUNT', 'Choose Count'), ('CHOOSE_CREDITS', 'Choose Credits')], max_length=20)),
                ('required_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('required_credits', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_groups', to='planner.curriculum')),
            ],
        ),
        migrations.CreateModel(
            name='RequirementCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curriculum_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_courses', to='planner.curriculumcourse')),
                ('requirement_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_courses', to='planner.requirementgroup')),
            ],
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('PASSED', 'Passed'), ('FAILED', 'Failed')], default='NOT_STARTED', max_length=20)),
                ('grade', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('curriculum_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_courses', to='planner.curriculumcourse')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_courses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='curriculumcourse',
            constraint=models.UniqueConstraint(fields=('curriculum', 'course'), name='unique_course_per_curriculum'),
        ),
        migrations.AddConstraint(
            model_name='prerequisite',
            constraint=models.UniqueConstraint(fields=('course', 'prerequisite'), name='unique_prerequisite'),
        ),
        migrations.AddConstraint(
            model_name='prerequisite',
            constraint=models.CheckConstraint(condition=models.Q(('course', models.F('prerequisite')), _negated=True), name='course_cannot_require_itself'),
        ),
        migrations.AddConstraint(
            model_name='requirementcourse',
            constraint=models.UniqueConstraint(fields=('curriculum_course', 'requirement_group'), name='unique_course_per_requirement'),
        ),
        migrations.AddConstraint(
            model_name='studentcourse',
            constraint=models.UniqueConstraint(fields=('student', 'curriculum_course'), name='unique_student_course'),
        ),
    ]
