# Generated by Django 5.2.17 on 2026-09-13 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirementgroup',
            name='overflow_to',
            field=models.ForeignKey(blank=True, help_text='Optional requirement group that receives excess completed credits.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overflowed_from', to='planner.requirementgroup'),
        ),
        migrations.AddConstraint(
            model_name='requirementgroup',
            constraint=models.CheckConstraint(condition=models.Q(('id', models.F('overflow_to')), _negated=True), name='requirement_group_cannot_overflow_to_itself'),
        ),
    ]
